/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frams;

import Entity.CasherClass;
import Entity.TypeCasherTransaction;
import Utilities.Tools;
import java.awt.Dimension;

/**
 *
 * @author mosta
 */
public class CasherTowPanel extends javax.swing.JPanel {

    /**
     * Creates new form CasherTowPanel
     */
    CasherClass cash;
    Dimension dim;
    public CasherTowPanel() {
        initComponents();
        cash = new CasherClass();
        dim = new Dimension( 475, 165);
        Tools.setBackground(background, dim, "bg4.jpg");
        txtBalance.setText(cash.getBalanceCasherTwo()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        debit = new javax.swing.JButton();
        credit = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الرصيد");

        txtBalance.setFont(new java.awt.Font("VIP Hala Bold", 1, 24)); // NOI18N
        txtBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(txtBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(265, 13, 202, 143);

        txtamount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtamount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtamount.setText("0.0");
        txtamount.setNextFocusableComponent(debit);
        txtamount.setSelectionStart(0);
        add(txtamount);
        txtamount.setBounds(12, 13, 228, 49);

        debit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        debit.setText("ايداع");
        debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitActionPerformed(evt);
            }
        });
        add(debit);
        debit.setBounds(12, 68, 228, 41);

        credit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        credit.setText("سحب");
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        add(credit);
        credit.setBounds(12, 115, 228, 41);
        add(background);
        background.setBounds(0, 0, 480, 170);
    }// </editor-fold>//GEN-END:initComponents

    private void debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitActionPerformed
        // TODO add your handling code here:
        double amount = Double.parseDouble(txtamount.getText());
        boolean issave = cash.SaveTransactionBetweenCasher(amount, TypeCasherTransaction.CasherTwoCredit);
        if(issave){
            txtBalance.setText(new CasherClass().getBalanceCasherTwo()+"");
            txtamount.setText("0.00");
        }
    }//GEN-LAST:event_debitActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        double amount = Double.parseDouble(txtamount.getText());
        double balance = Double.parseDouble(txtBalance.getText());
        if(amount > balance){
            Tools.showErrorMsg("لايمكن سحب المبلغ المطلوب");
        }else{
            boolean issave = cash.SaveTransactionBetweenCasher(amount, TypeCasherTransaction.CasherTwoDebit);
            if(issave){
                txtBalance.setText(new CasherClass().getBalanceCasherTwo()+"");
            }        
        
        }
       txtamount.setText("0.00");

        
    }//GEN-LAST:event_creditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton credit;
    private javax.swing.JButton debit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtBalance;
    private javax.swing.JTextField txtamount;
    // End of variables declaration//GEN-END:variables
}
