/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frams;

import Utilities.Tools;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author mosta
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    public MainFrame() {
        initComponents();
        background.setLocation(0, 0);
        background.setSize(dim);
        background.setPreferredSize(dim);
        ImageIcon bg = new ImageIcon(new ImageIcon(Toolkit.getDefaultToolkit().getClass().getResource("/icons/bg.jpg")).getImage().getScaledInstance(dim.width, dim.height, Image.SCALE_DEFAULT));
        background.setIcon(bg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suppliers = new javax.swing.JLabel();
        client = new javax.swing.JLabel();
        items = new javax.swing.JLabel();
        suppliers1 = new javax.swing.JLabel();
        suppliers2 = new javax.swing.JLabel();
        suppliers3 = new javax.swing.JLabel();
        suppliers4 = new javax.swing.JLabel();
        suppliers5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        suppliers.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        suppliers.setForeground(new java.awt.Color(0, 51, 255));
        suppliers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cash.png"))); // NOI18N
        suppliers.setText("تحصيلات");
        suppliers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppliers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppliers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suppliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliersMouseExited(evt);
            }
        });
        getContentPane().add(suppliers);
        suppliers.setBounds(310, 250, 220, 190);

        client.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        client.setForeground(new java.awt.Color(0, 51, 255));
        client.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clint.png"))); // NOI18N
        client.setText("العملاء");
        client.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        client.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        client.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clientMouseExited(evt);
            }
        });
        getContentPane().add(client);
        client.setBounds(790, 40, 220, 190);

        items.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        items.setForeground(new java.awt.Color(0, 51, 255));
        items.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shelves.png"))); // NOI18N
        items.setText("الاصناف");
        items.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        items.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        items.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemsMouseExited(evt);
            }
        });
        getContentPane().add(items);
        items.setBounds(790, 250, 220, 190);

        suppliers1.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        suppliers1.setForeground(new java.awt.Color(0, 51, 255));
        suppliers1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppliers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/courier.png"))); // NOI18N
        suppliers1.setText("الموردين");
        suppliers1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppliers1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppliers1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suppliers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliers1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliers1MouseExited(evt);
            }
        });
        getContentPane().add(suppliers1);
        suppliers1.setBounds(790, 470, 220, 190);

        suppliers2.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        suppliers2.setForeground(new java.awt.Color(0, 51, 255));
        suppliers2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppliers2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/payment_1.png"))); // NOI18N
        suppliers2.setText("مدفوعات");
        suppliers2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppliers2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppliers2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suppliers2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliers2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliers2MouseExited(evt);
            }
        });
        getContentPane().add(suppliers2);
        suppliers2.setBounds(310, 40, 220, 190);

        suppliers3.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        suppliers3.setForeground(new java.awt.Color(0, 51, 255));
        suppliers3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppliers3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/selling.png"))); // NOI18N
        suppliers3.setText("مشتريات");
        suppliers3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppliers3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppliers3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suppliers3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliers3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliers3MouseExited(evt);
            }
        });
        getContentPane().add(suppliers3);
        suppliers3.setBounds(550, 40, 220, 190);

        suppliers4.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        suppliers4.setForeground(new java.awt.Color(0, 51, 255));
        suppliers4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppliers4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/software.png"))); // NOI18N
        suppliers4.setText("تقارير");
        suppliers4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppliers4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppliers4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suppliers4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliers4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliers4MouseExited(evt);
            }
        });
        getContentPane().add(suppliers4);
        suppliers4.setBounds(550, 470, 220, 190);

        suppliers5.setFont(new java.awt.Font("VIP Hala Bold", 1, 18)); // NOI18N
        suppliers5.setForeground(new java.awt.Color(0, 51, 255));
        suppliers5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suppliers5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buy.png"))); // NOI18N
        suppliers5.setText("مبيعات");
        suppliers5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppliers5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppliers5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suppliers5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliers5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suppliers5MouseExited(evt);
            }
        });
        getContentPane().add(suppliers5);
        suppliers5.setBounds(550, 250, 220, 190);

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(background);
        background.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMouseClicked
        // TODO add your handling code here:
        clickPanel(client);
        ClintFrame c = new ClintFrame();
        Tools.openJFram(c, "العملاء");
    }//GEN-LAST:event_clientMouseClicked

    private void clientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientMouseExited
        // TODO add your handling code here:
        exitPanel(client);
    }//GEN-LAST:event_clientMouseExited

    private void itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseClicked
        // TODO add your handling code here:
        clickPanel(items);
        itemsFrame items = new itemsFrame();
        Tools.openJFram(items, "الاصناف");
        
        
    }//GEN-LAST:event_itemsMouseClicked

    private void itemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsMouseExited
        // TODO add your handling code here:
        exitPanel(items);
    }//GEN-LAST:event_itemsMouseExited

    private void suppliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersMouseClicked
        // TODO add your handling code here:
        clickPanel(suppliers);
    }//GEN-LAST:event_suppliersMouseClicked

    private void suppliersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliersMouseExited
        // TODO add your handling code here:
        exitPanel(suppliers);
    }//GEN-LAST:event_suppliersMouseExited

    private void suppliers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers1MouseClicked

    private void suppliers1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers1MouseExited

    private void suppliers2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers2MouseClicked

    private void suppliers2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers2MouseExited

    private void suppliers3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers3MouseClicked

    private void suppliers3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers3MouseExited

    private void suppliers4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers4MouseClicked

    private void suppliers4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers4MouseExited

    private void suppliers5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers5MouseClicked

    private void suppliers5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliers5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliers5MouseExited
    
    private void clickPanel(JLabel lable){
        lable.setBorder(BorderFactory.createLoweredBevelBorder());
    }
    private void exitPanel(JLabel lable){
        lable.setBorder(BorderFactory.createRaisedSoftBevelBorder());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel client;
    private javax.swing.JLabel items;
    private javax.swing.JLabel suppliers;
    private javax.swing.JLabel suppliers1;
    private javax.swing.JLabel suppliers2;
    private javax.swing.JLabel suppliers3;
    private javax.swing.JLabel suppliers4;
    private javax.swing.JLabel suppliers5;
    // End of variables declaration//GEN-END:variables
}
