SELECT 
(SELECT IFNULL(SUM(Debit),0) FROM casher WHERE id_masary_pay IS NOT NULL AND date_casher = curdate()) AS POS_PAY ,
(SELECT IFNULL(SUM(Debit),0) FROM casher WHERE id_Receipt IS NOT NULL AND date_casher = curdate()) AS Recipt , 
(SELECT IFNULL(SUM(Debit),0) FROM casher WHERE id_salesInvoic IS NOT NULL AND date_casher = curdate()) AS Sales ,
(SELECT IFNULL(SUM(Debit),0) FROM casher WHERE id_Send_Receive IS NOT NULL AND date_casher = curdate()) AS Send_VfCash ,
(SELECT IFNULL(SUM(Debit),0) FROM casher WHERE id_Solf IS NOT NULL AND date_casher = curdate()) AS Solfa ,
(SELECT POS_PAY +Recipt+Sales+ Send_VfCash + Solfa) AS Total_Import,
(SELECT IFNULL(SUM(Creditor),0) FROM casher WHERE id_masary_sell IS NOT NULL AND date_casher = curdate()) AS POS_Sell ,
(SELECT IFNULL(SUM(Creditor),0) FROM casher WHERE id_PaymentReceipt IS NOT NULL AND date_casher = curdate()) AS Payment, 
(SELECT IFNULL(SUM(Creditor),0) FROM casher WHERE id_purchaseInvoice IS NOT NULL AND date_casher = curdate()) AS Purchases,
(SELECT IFNULL(SUM(Creditor),0) FROM casher WHERE id_Send_Receive IS NOT NULL AND date_casher = curdate()) AS Receive_VfCash, 
(SELECT IFNULL(SUM(Creditor),0) FROM casher WHERE id_fees IS NOT NULL AND date_casher = curdate()) AS Feeses,
(SELECT POS_Sell + Payment +  Purchases +Receive_VfCash + Feeses ) AS Total_Export ,
(SELECT IFNULL(oldBalance,0) FROM finallyday WHERE dateFinally = curdate()) AS Old_Balance,
(SELECT Old_Balance + Total_Import - Total_Export) AS Balance